BEGIN TRANSACTION;
BEGIN DEFERRED TRANSACTION;
BEGIN IMMEDIATE TRANSACTION;

INSERT OR ROLLBACK INTO Activite (Type, Date, Prix, Description)
VALUES (1, '2024-01-10', 5.5, 'Pas intéressant');

COMMIT;
ROLLBACK;

